language: ruby
cache: bundler

before_install:
  - gem install "rubygems-update:<3.0.0" --no-document
  - update_rubygems
  - gem install bundler -v 1.17.3

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - 2.5.1
  - ruby-head

gemfile:
  - gemfiles/Gemfile.rails-3-0-stable
  - gemfiles/Gemfile.rails-3-1-stable
  - gemfiles/Gemfile.rails-3-2-stable
  - gemfiles/Gemfile.rails-4-0-stable
  - gemfiles/Gemfile.rails-4-1-stable
  - gemfiles/Gemfile.rails-4-2-stable
  - gemfiles/Gemfile.rails-5-0-stable
  - gemfiles/Gemfile.rails-5-1-stable
  - gemfiles/Gemfile.rails-5-2-stable
  - Gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-2-stable
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-2-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: 2.3.4
      gemfile: Gemfile
    - rvm: 2.2.7
      gemfile: Gemfile
    - rvm: 2.1.10
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
script: 'bundle exec rake'

jobs:
  include:
    - stage: documentation
      script: './bin/deploy_docs'
      rvm: 2.5.1
      gemfile: Gemfile

notifications:
  email:
    recipients:
      - hunterae@gmail.com
    on_failure: change
    on_success: never
