language: ruby
cache: bundler

before_install:
  - gem update bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1

gemfile:
  - gemfiles/Gemfile.rails-3-0-stable
  - gemfiles/Gemfile.rails-3-1-stable
  - gemfiles/Gemfile.rails-3-2-stable
  - gemfiles/Gemfile.rails-4-0-stable
  - gemfiles/Gemfile.rails-4-1-stable
  - gemfiles/Gemfile.rails-4-2-stable
  - gemfiles/Gemfile.rails-5-0-stable
  - gemfiles/Gemfile.rails-5-1-stable
  - Gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-1-stable
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5-0-stable
    - rvm: 2.1.10
      gemfile: Gemfile
script: 'bundle exec rake'

jobs:
  include:
    - stage: documentation
      script: './bin/deploy_docs'
      rvm: 2.4.1
      gemfile: Gemfile

notifications:
  email:
    recipients:
      - hunterae@gmail.com
    on_failure: change
    on_success: never
