# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql2
  database: blocks_dev
  username: root
  password: 
  host: 127.0.0.1
  encoding: utf8
  pool: 8

test: &test
  adapter: mysql2
  database: blocks_test
  username: root
  password: 
  host: 127.0.0.1
  encoding: utf8

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *test